# Generated by Django 4.0.2 on 2026-02-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_order',
            field=models.IntegerField(default=0, help_text='عدد کوچکتر = نمایش زودتر', verbose_name='ترتیب نمایش'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='این محصول در بخش پرفروش\u200cها نمایش داده شود؟', verbose_name='محصول ویژه (پرفروش)'),
        ),
    ]
